### ISSUE TITLE
Remove node_modules from root of the repo

### ISSUE THREAD

**Issue by pringon** [cube-academy/legal-negotiator-server#1]
Running `git rm -r --cached node_modules` should do the trick

**Comment by jimmysafe** [comment]
Hey Dan whassup!? how are you doing? 
Thanks for the hint, i didn't notice it when pushing it!

**Comment by pringon** [comment]
I'm good, currently doing a devops/backend placement in cambridge.

Glad to see you crushing it at Cube 😉
